// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDashboardData(arg1:string):Promise<string>;

export function LoadLocalJSON(arg1:string,arg2:string):Promise<string>;

export function LoadSettings():Promise<string>;

export function OpenURLInBrowser(arg1:string):Promise<void>;

export function SaveLocalJSON(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSettings(arg1:string):Promise<string>;

export function StartDepoProxy(arg1:string):Promise<string>;

export function StopDepoProxy(arg1:string):Promise<void>;

export function TriggerSyncAndAnalysis(arg1:string,arg2:boolean):Promise<string>;
