// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDashboardData(arg1) {
  return window['go']['main']['App']['GetDashboardData'](arg1);
}

export function LoadLocalJSON(arg1, arg2) {
  return window['go']['main']['App']['LoadLocalJSON'](arg1, arg2);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenURLInBrowser(arg1) {
  return window['go']['main']['App']['OpenURLInBrowser'](arg1);
}

export function SaveLocalJSON(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveLocalJSON'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartDepoProxy(arg1) {
  return window['go']['main']['App']['StartDepoProxy'](arg1);
}

export function StopDepoProxy(arg1) {
  return window['go']['main']['App']['StopDepoProxy'](arg1);
}

export function TriggerSyncAndAnalysis(arg1, arg2) {
  return window['go']['main']['App']['TriggerSyncAndAnalysis'](arg1, arg2);
}
